apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: recipe-box
    component: web
spec:
  ports:
  - port: 9303
    targetPort: 8080
  selector:
    app: recipe-box
    component: web


