apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: recipe-box
    component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-box
      component: web
  template:
    metadata:
      labels:
        app: recipe-box
        component: web
    spec:
      containers:
        - name: web
          image: bcmehrman/shouter:0.0.2
          envFrom:
            - configMapRef:
                name: clojure
